<?php
/* @var $this PropertyController */
/* @var $model Property */

$this->breadcrumbs=array(
	'Properties'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Property', 'url'=>array('index')),
	array('label'=>'Create Property', 'url'=>array('create')),
	array('label'=>'Update Property', 'url'=>array('update', 'id'=>$model->propid)),
	array('label'=>'Delete Property', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->propid),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Property', 'url'=>array('admin')),
);
?>

<h1>View Property #<?php echo $model->propid; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'propid',
		'type',
		'fsale',
		'frent',
		'fsrent',
		'hsale',
		'hrent',
		'hsrent',
		'exclusive',
		'totcovar',
		'comar',
		'covar',
		'uncovar',
		'landarea',
		'disttosea',
		'nobed',
		'nobath',
		'seaview',
		'sideseaview',
		'gardenview',
		'cityview',
		'mountainview',
		'swview',
		'otherview',
		'floor',
		'stage',
		'swimpool',
		'sprivate',
		'parking',
		'storeroom',
		'address',
		'area',
		'areacode',
		'city',
		'country',
		'projectid',
		'description',
		'ownerid',
		'price1',
		'amount',
		'addedby',
		'addeddt',
		'vat',
		'descriptionru',
		'name',
		'nameru',
		'price2',
		'firstline',
		'unparking',
		'teniscourt',
		'titledeed',
		'sold',
		'rent',
		'buildfact',
		'road',
		'comunal',
		'electricity',
		'water',
		'projectar',
		'comision',
		'chcomision',
		'landtype',
		'renttype',
		'tenants',
		'furniture',
		'sleep',
		'deposit',
		'conditioner',
		'heating',
		'pets',
		'smoking',
		'price3',
		'price4',
		'price5',
		'notes',
		'notesru',
		'lat',
		'lng',
		'fake',
	),
)); ?>
